name: Build and Vitest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Test

    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: pnpm-setup
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: pnpm install
        run: pnpm install

      - name: build test
        run: pnpm run build

      - name: exec vitest
        run: pnpm run test
